package com.example.shoppingAndNotesListApp.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Entity representing a shopping list "header" (list metadata).
 *
 * This table stores:
 * - list name
 * - creation/update time
 * - counters for items
 * - relation to items via IDs string
 *
 * Used as parent entity for ShopListItem records.
 */
@Entity(tableName = "shopping_list_names")
data class ShopListNameItem(

    // ================= PRIMARY KEY =================

    /**
     * Unique identifier of the shopping list.
     * Auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int? ,

    // ================= BASIC INFO =================

    /**
     * Name of the shopping list.
     * Example: "Groceries", "Electronics", etc.
     */
    @ColumnInfo(name = "name")
    val name: String ,

    /**
     * Timestamp of list creation or last update.
     * Stored as formatted String.
     */
    @ColumnInfo(name = "time")
    val time: String ,

    // ================= ITEMS STATISTICS =================

    /**
     * Total number of items in the list.
     * Includes both checked and unchecked items.
     */
    @ColumnInfo(name = "allItemCounter")
    val allItemCounter: Int ,

    /**
     * Number of completed (checked) items.
     */
    @ColumnInfo(name = "checkedItemsCounter")
    val checkedItemsCounter: Int ,

    // ================= RELATION DATA =================

    /**
     * List of item IDs stored as a single String.
     *
     * Example format:
     * "1,2,3,4"
     *
     * Used for lightweight relation instead of full JOIN.
     */
    @ColumnInfo(name = "itemsIds")
    val itemsIds: String?

) : Serializable
